/**
 * Recording (Phase B proof) — `/app/recording`.
 *
 * Mirrors the Recording demo at /Kaptire Website Templates/kooper-recording-demo.html.
 *
 * Server-render the hero strip and active-context card, then mount the
 * `<RecordingFlow>` client component for the icon-tap state and live
 * AI narrative. In production:
 *   · `Lock note` calls a server action that writes a row to
 *     recording_events (universal contract).
 *   · The AI narrative is generated by an Anthropic streaming server
 *     action that accepts the structured fields and returns one
 *     paragraph in the provider voice.
 *
 * Hard-coded "Personal care · Edward Banda · Craig Musara" focus for
 * proof.
 */
import { RecordingFlow } from "@/components/recording/RecordingFlow";

export default function RecordingPage() {
  return (
    <main>
      <section className="bg-black text-white">
        <div className="container-kapture py-10">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-end">
            <div className="lg:col-span-8">
              <div className="font-mono text-[0.6875rem] font-semibold uppercase tracking-[0.12em] text-[#FFD400] mb-3 inline-flex items-center gap-2">
                <span aria-hidden className="inline-block h-[2px] w-[18px] bg-[#FFD400]" />
                3 TAPS · AI NARRATIVE · CQC EVIDENCE
              </div>
              <h1 className="font-display text-[clamp(2.25rem,4.5vw,3.25rem)] leading-[1.05] tracking-[-0.02em] mb-3">
                Tap the icons. The note writes itself.
              </h1>
              <p className="font-serif italic text-base lg:text-lg text-white/75 max-w-2xl leading-relaxed">
                Every interaction captures <strong className="not-italic text-white">how</strong> care was delivered — level of support, consent, dignity, risks, outcomes, time. AI turns the taps into a CQC-ready narrative. Inspector questions get answered before they’re asked.
              </p>
            </div>
            <div className="lg:col-span-4">
              <div className="bg-[#1A1A1A] border border-[#2A2A2A] rounded-2xl p-5">
                <div className="font-mono text-[0.6875rem] uppercase tracking-[0.12em] text-[#9A9A9A] mb-3">Active context</div>
                <ul className="space-y-2 text-sm">
                  <li className="flex justify-between"><span className="text-white/60">Carer</span><span className="font-medium">Craig Musara</span></li>
                  <li className="flex justify-between"><span className="text-white/60">Resident</span><span className="font-medium">Edward Banda</span></li>
                  <li className="flex justify-between"><span className="text-white/60">Visit</span><span className="font-mono text-xs">07:42 · Morning round</span></li>
                  <li className="flex justify-between"><span className="text-white/60">Care plan</span><span className="font-medium">v4 (current)</span></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="container-kapture py-10">
        <RecordingFlow />
      </section>
    </main>
  );
}
