/**
 * Family (Phase C proof) — `/app/family`.
 *
 * Mirrors /Kaptire Website Templates/kooper-family.html. PWA-style,
 * mobile-first, family-facing. Centred on a daily AI summary written
 * for a daughter, not a clinician.
 *
 * Production specifics:
 *   · Each family user is bound to a resident via family_resident_consent.
 *   · Daily summary text is generated by an Anthropic server action
 *     using the resident's recording_events for the day.
 *   · The PrivacyBoundary component visualises the RBAC fields and
 *     opens family_access_requests rows.
 */
import { PrivacyBoundary } from "@/components/family/PrivacyBoundary";
import { BottomTabBar } from "@/components/resident/BottomTabBar";

export default function FamilyPage() {
  return (
    <main className="bg-[#FAFAF7] min-h-screen pb-24">
      <header className="max-w-[720px] mx-auto px-5 pt-6 pb-3">
        <div className="flex items-center gap-4 mb-3">
          <div className="w-14 h-14 rounded-full bg-[#FFD400] text-black font-display font-bold flex items-center justify-center border-[3px] border-white shadow-md">EB</div>
          <div>
            <div className="text-xs text-[#6B7280]">For Sarah · viewing</div>
            <h1 className="font-display font-semibold text-2xl">Mr Edward Banda <span className="text-[#6B7280] font-normal text-base">· Dad</span></h1>
            <div className="text-xs text-[#6B7280] mt-0.5">Settled at Draycott · last seen 14:18</div>
          </div>
        </div>
        <div className="rounded-full inline-flex items-center gap-1.5 border border-dashed border-[#6B7280] bg-black/[0.04] px-3 py-1.5 text-xs text-[#3A3A3A]">
          <span aria-hidden>🔒</span>
          <span><strong className="text-black">The care plan stays private.</strong> You see daily summaries, photos, and what Dad asked us to share.</span>
        </div>
      </header>

      <section className="max-w-[720px] mx-auto px-5 mb-5">
        <div className="rounded-[18px] bg-black text-white p-6">
          <div className="flex items-center justify-between mb-3">
            <div className="font-mono text-[0.6875rem] font-semibold uppercase tracking-[0.12em] text-[#FFD400] inline-flex items-center gap-2">
              <span aria-hidden className="inline-block h-[2px] w-[18px] bg-[#FFD400]" />
              TODAY · WED 6 MAY
            </div>
            <span className="rounded-full bg-[#FFD400] text-black px-2 py-0.5 text-[0.625rem] font-mono font-semibold">AI · DAILY SUMMARY</span>
          </div>
          <p className="font-serif text-base lg:text-lg leading-relaxed text-white/95">
            Dad had a calm day. Personal care this morning at <strong>07:42</strong> with Craig — he was in a bright mood and asked after you. He ate well at breakfast (porridge, banana), enjoyed a sing-along with Mary at <strong>14:30</strong>, and had his Sinatra on for the afternoon.
          </p>
          <p className="font-serif text-sm text-white/70 italic mt-2">Nothing to worry about. Sister Anne is on shift tonight.</p>
        </div>
      </section>

      <section className="max-w-[720px] mx-auto px-5 mb-5">
        <div className="rounded-[18px] border border-[#FCD34D] bg-gradient-to-b from-[#FFFBEB] to-[#FFF8E1] p-5">
          <div className="flex items-center gap-3 mb-2">
            <div className="w-10 h-10 rounded-2xl bg-[#FFD400] flex items-center justify-center text-xl">📞</div>
            <div className="flex-1">
              <div className="font-display font-semibold">Dad is calling at 17:00</div>
              <div className="text-xs text-black/80">Sister Anne will help him pick up on his iPad. The boys can wave too.</div>
            </div>
          </div>
        </div>
      </section>

      <section className="max-w-[720px] mx-auto px-5">
        <PrivacyBoundary />
      </section>

      <BottomTabBar
        tabs={[
          { href: "/app/family",         label: "Home",    icon: <span aria-hidden>🏠</span> },
          { href: "/app/family/photos",  label: "Photos",  icon: <span aria-hidden>📷</span> },
          { href: "/app/family/calls",   label: "Calls",   icon: <span aria-hidden>📞</span> },
          { href: "/app/family/message", label: "Message", icon: <span aria-hidden>💬</span> },
        ]}
      />
    </main>
  );
}
