/**
 * RecordingFlow — the icon-tap → AI narrative client component.
 *
 * Drives the full Recording demo loop:
 *   · Three icon-tap steps (level of support, consent + dignity, outcome)
 *   · Live narrative regeneration on every tap
 *   · Voice-note injection
 *   · Lock + edit + redraft handlers
 *
 * Server-side equivalent: in production, on `Lock note`, this writes a
 * row to `recording_events` and the AI narrative is generated by an
 * Anthropic streaming server action. Here it's all in-memory for the
 * proof.
 */
"use client";

import { useMemo, useState } from "react";

type Support = "independent" | "prompted" | "assisted" | "full";
type Consent = "verbal" | "non-verbal" | "implied" | "refused";
type Dignity = "maintained" | "compromised";
type Outcome = "routine" | "near-miss" | "incident" | "abc";

const SUPPORT_TILES: { id: Support; label: string }[] = [
  { id: "independent", label: "Independent" },
  { id: "prompted",    label: "Prompted" },
  { id: "assisted",    label: "Assisted" },
  { id: "full",        label: "Full hands-on" },
];

const CONSENT_TILES: { id: Consent; label: string }[] = [
  { id: "verbal",     label: "Verbal yes" },
  { id: "non-verbal", label: "Non-verbal" },
  { id: "implied",    label: "Implied" },
  { id: "refused",    label: "Refused" },
];

const DIGNITY_TILES: { id: Dignity; label: string }[] = [
  { id: "maintained",  label: "Maintained" },
  { id: "compromised", label: "Briefly compromised" },
];

const OUTCOME_TILES: { id: Outcome; label: string }[] = [
  { id: "routine",   label: "Routine" },
  { id: "near-miss", label: "Near miss" },
  { id: "incident",  label: "Incident" },
  { id: "abc",       label: "Behaviour (ABC)" },
];

const SUPPORT_VERB: Record<Support, string> = {
  independent: "completed independently with light supervision",
  prompted:    "completed with verbal prompts",
  assisted:    "received hand-over-hand support",
  full:        "received full hands-on care",
};
const CONSENT_PHRASE: Record<Consent, string> = {
  verbal:       "gave verbal consent before the wash",
  "non-verbal": "indicated non-verbal consent (calm posture, settled breathing)",
  implied:      "gave implied consent — care was anticipated and welcomed",
  refused:      "initially refused; carer paused, returned 5 min later, consent obtained",
};
const DIGNITY_PHRASE: Record<Dignity, string> = {
  maintained:  "Dignity was maintained throughout — privacy curtain drawn, room temperature checked.",
  compromised: "Dignity was briefly compromised during the transfer; carer apologised, repositioned, and continued.",
};
const OUTCOME_PHRASE: Record<Outcome, string> = {
  routine:     "Skin observed: no new redness on sacrum or heels. Mood was bright; he asked after Sister Anne.",
  "near-miss": "A near miss was logged — Edward steadied himself on the rail before any fall. No injury. Falls protocol triggered automatically.",
  incident:    "An incident occurred during the transfer. First-aid steps followed; manager notified within 5 minutes; family contact opened.",
  abc:         "Behaviour event captured to ABC chart. Antecedent, behaviour, consequence noted. De-escalation worked within 10 minutes.",
};

export function RecordingFlow() {
  const [support, setSupport] = useState<Support>("assisted");
  const [consent, setConsent] = useState<Consent>("verbal");
  const [dignity, setDignity] = useState<Dignity>("maintained");
  const [outcome, setOutcome] = useState<Outcome>("routine");
  const [voice,   setVoice]   = useState<string>("");
  const [locked,  setLocked]  = useState<boolean>(false);

  const narrative = useMemo(() => {
    const tone =
      support === "full"
        ? "full hands-on personal care"
        : support === "assisted"
        ? "assisted personal care"
        : support === "prompted"
        ? "prompted personal care"
        : "independent personal care with light supervision";
    const v = voice ? ` Carer added: "${voice}".` : "";
    return `At 07:42 on 6 May 2026, Mr Banda received ${tone} from carer Craig Musara. He ${CONSENT_PHRASE[consent]}. Edward ${SUPPORT_VERB[support]} with the wash, shave and oral care. ${DIGNITY_PHRASE[dignity]} His preferred talc and body wash were used. ${OUTCOME_PHRASE[outcome]}${v} Care concluded at 08:04 (22 minutes) with Edward dressed, comfortable and seated for breakfast.`;
  }, [support, consent, dignity, outcome, voice]);

  return (
    <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
      <div className="lg:col-span-7 space-y-6">
        <Step number={1} title="Level of support" caption="How much help did Edward need this morning?">
          <TileGrid value={support} onChange={setSupport} tiles={SUPPORT_TILES} cols={4} />
        </Step>

        <Step number={2} title="Consent & dignity" caption="How did Edward indicate consent? Was dignity maintained?">
          <Sublabel>Consent</Sublabel>
          <TileGrid value={consent} onChange={setConsent} tiles={CONSENT_TILES} cols={4} />
          <div className="mt-4">
            <Sublabel>Dignity</Sublabel>
            <TileGrid value={dignity} onChange={setDignity} tiles={DIGNITY_TILES} cols={2} yellowSelected />
          </div>
        </Step>

        <Step number={3} title="Outcome & time" caption="Anything noteworthy? Any event? Time captured automatically.">
          <TileGrid value={outcome} onChange={setOutcome} tiles={OUTCOME_TILES} cols={4} />
          <div className="mt-4 rounded-xl bg-[#F5F5F5] px-4 py-3 flex items-center justify-between text-sm">
            <span className="font-mono">Time captured</span>
            <span className="font-mono font-semibold">07:42 → 08:04 · 22 min</span>
          </div>
        </Step>

        <div className="rounded-2xl bg-black text-white p-5 lg:p-6">
          <div className="font-display font-semibold mb-2">Add voice context (optional)</div>
          <p className="text-sm text-white/70 mb-4">Press the mic for anything that needs a sentence — kooper · ai weaves it into the official note. The 3 taps are enough on their own.</p>
          <div className="flex flex-wrap items-center gap-3">
            <button
              onClick={() => {
                const samples = [
                  "Edward sang along to a Sinatra track during the shave",
                  "He asked twice when his daughter Sarah is visiting",
                  "Pressure-relief cushion repositioned per protocol",
                  "Mild dryness around left ankle, photo to wound care",
                ];
                setVoice(samples[Math.floor(Math.random() * samples.length)]);
              }}
              className="bg-transparent border border-white text-white rounded-[10px] px-4 py-2 text-sm font-medium hover:bg-white hover:text-black transition"
            >
              Hold to add voice
            </button>
            <button
              onClick={() => setLocked(true)}
              className="bg-[#FFD400] text-black rounded-[10px] px-4 py-2 text-sm font-semibold hover:bg-[#F5B400] transition"
            >
              {locked ? "Locked ✓" : "Lock note"}
            </button>
          </div>
          {voice && (
            <div className="mt-3 text-xs text-white/70">Voice woven: <em className="text-white/90">"{voice}"</em></div>
          )}
        </div>
      </div>

      <div className="lg:col-span-5">
        <div className="rounded-[18px] border border-[#E5E7EB] bg-gradient-to-b from-white to-[#FAFAFA] p-6">
          <div className="flex items-center justify-between mb-3">
            <div className="font-display font-semibold text-sm">CQC-ready note</div>
            <span className="font-mono text-[0.625rem] font-semibold tracking-[0.04em] uppercase bg-[#FFD400] text-black rounded px-1.5 py-0.5">AI · CLAUDE</span>
          </div>
          <p className="font-serif text-[0.9375rem] leading-[1.65] text-[#1A1A1A]">{narrative}</p>
          <div className="mt-4 pt-4 border-t border-[#ECEAE3] flex flex-wrap gap-2">
            <button onClick={() => setLocked(true)} className="bg-black text-white rounded-[10px] px-3 py-1.5 text-xs font-medium hover:bg-[#1A1A1A]">{locked ? "Locked ✓" : "Lock note"}</button>
            <button onClick={() => setLocked(false)} className="text-xs font-medium text-black underline-offset-4 underline">Edit before locking</button>
          </div>
        </div>
      </div>
    </div>
  );
}

function Step({ number, title, caption, children }: { number: number; title: string; caption: string; children: React.ReactNode }) {
  return (
    <section className="rounded-2xl bg-white border border-[#ECEAE3] p-5 lg:p-6">
      <div className="flex items-center gap-3 mb-4">
        <span className="w-7 h-7 rounded-full bg-[#FFD400] text-black font-mono font-bold text-[0.8125rem] flex items-center justify-center">{number}</span>
        <div>
          <div className="font-display font-semibold text-base">{title}</div>
          <div className="text-xs text-[#6B7280]">{caption}</div>
        </div>
      </div>
      {children}
    </section>
  );
}

function Sublabel({ children }: { children: React.ReactNode }) {
  return <div className="font-mono text-[0.6875rem] uppercase tracking-[0.06em] text-[#6B7280] mb-2">{children}</div>;
}

interface TileGridProps<T extends string> {
  value: T;
  onChange: (v: T) => void;
  tiles: { id: T; label: string }[];
  cols: 2 | 4;
  yellowSelected?: boolean;
}
function TileGrid<T extends string>({ value, onChange, tiles, cols, yellowSelected }: TileGridProps<T>) {
  const colsCls = cols === 4 ? "grid-cols-2 sm:grid-cols-4" : "grid-cols-2";
  return (
    <div className={["grid gap-3", colsCls].join(" ")}>
      {tiles.map((t) => {
        const selected = value === t.id;
        const cls = selected
          ? yellowSelected
            ? "bg-[#FFD400] text-black border-[#FFD400]"
            : "bg-black text-white border-black"
          : "bg-white text-black border-[#E5E7EB] hover:border-black";
        return (
          <button
            key={t.id}
            type="button"
            onClick={() => onChange(t.id)}
            className={[
              "aspect-square rounded-[18px] border flex flex-col items-center justify-center gap-2 px-3 py-2 transition",
              cls,
            ].join(" ")}
          >
            <span className="text-xs font-medium">{t.label}</span>
          </button>
        );
      })}
    </div>
  );
}
